name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - 'Makefile'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - 'Makefile'

env:
  llvm_version: 15.0.6

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-${{ env.llvm_version }}
          key: llvm-${{ env.llvm_version }}

      - name: Download LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          LLVM_VERSION=${{ env.llvm_version }} make llvm
          rm llvm-${{ env.llvm_version }}/*.tar.*

      - name: Make
        run: make
