name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  llvm_version: 15.0.6

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download llvm
        run: LLVM_VERSION=${{ env.llvm_version }} make llvm

      - name: Make
        run: make
